import DashboardLayout from "../../layouts/DashboardLayout";
import PageHeader from "../../components/ui/PageHeader";
import DataTable from "../../components/ui/DataTable";
import { exportToExcel } from "../../utils/exportToExcel";

export default function HistoryList() {
  const columns = [
    {
      key: "queryName",
      label: "Query Name",
    },
    {
      key: "user",
      label: "Generated By",
      render: (row) => row.user?.firstName,
    },
    {
      key: "createdAt",
      label: "Generated At",
      render: (row) => new Date(row.createdAt).toLocaleString(),
    },
  ];

  return (
    <DashboardLayout>
      <PageHeader title="Query History" subtitle="Generated Queries" />

      <DataTable columns={columns} data={[]} />
      <Button onClick={() => exportToExcel(history, "query-history")}>
        Export Excel
      </Button>
    </DashboardLayout>
  );
}
